name: Lint
on: [push]

jobs:
  lint:
    name: Lint application codebase
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run linter
        run: |
          yarn lint
        env:
          CI: true
      - name: Make a production build
        run: yarn build
